### ISSUE TITLE
✨ Feat : 미용실 예약

### ISSUE THREAD

**Issue by jeongwonkimo3o** [Shining-Jicheon-Stars/yjg-laravel-backend#34]
## 어떤 기능인가요?

> **미용실 예약 기능을 수행하는 컨트롤러**

- 일반 유저(학생)가 미용실 예약을 합니다.
- 예약 날짜, 예약 시간, 시술 서비스, 가격, 유저 정보

- (개인적 의견)  A유저가 예약할 때 B유저도 동시에 같은 시간에 예약함으로 발생하는 충돌 방지도 고려해야 할 거 같습니다 (회의실 예약도 마찬가지로)

**Comment by Hyn2** [comment]
필터링 기능 추가해서 구현
